config/routes.rb
Rails.application.routes.draw do
  
  resources :tweets
  root 'tweets#index'
  get 'tweets/:id/show',to:'tweets#show'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :messesge, presence: true
  validates :messesge, length:{maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
    logger.debug("test")
  end
  def new
    @tweet = Tweet.new
  end
  def create
    @tweet = Tweet.new(messesge: params[:tweet][:messesge],tdate: Time.current)
     if @tweet.save
       redirect_to '/'
     else
       render'new'
     end 
  end
  def destroy
     tweet = Tweet.find(params[:id])
     tweet.destroy
     redirect_to '/'
  end
  def edit
    @tweet = Tweet.find(params[:id])
  end
  def update
    @tweet = Tweet.find(params[:id])
    messesge = params[:tweet][:messesge]
    @tweet.update(messesge: messesge)
    redirect_to '/'
  end
  def show
    @tweets = Tweet.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tw</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header">
    <%=render "header" %>
      <center>
<table style="border-style: none;" border="1">
<td style="border-style: none;">ツイート<br><a href="#">1232</a></td>
<td style="border-style: none;">フォロー<br><a href="#">12352</a></td>
<td style="border-style: none;">フォロワー<br><a href="#">122</a></td>
<td style="border-style: none;">いいね<br><a href="#">12632</a></td>
</tr>
<div class="kindai">
  <img src="assets/kindai.png" width="150" height="150" style="border-radius:400px;" >
</div>
</table>
      </center>
      <hr>
  </div>
  <div id="sidebar">
    <%=render "sidebar" %>
  </div>
  <div id="content">
     <%= yield %>
  </div>
  <div id="footer">
    
    <%=render "footer" %>
  </div>
</body>
</html>

app/views/tweets/_header.html.erb
  <img src="assets/head.png" width=98%;>
　

app/views/tweets/_sidebar.html.erb
    <p>
     <font size="6">近畿大学</font><br>
     <a href="https://swdev-matuoka.c9users.io/">@kinkidaigakuPR</a>
    </p>
    近畿大学総務部広報室のTwitter公式アカウントです。
    近畿大学ホームページの更新情報を中心に、大学に関する情報を発信していきます。 
    個別DMでのお問い合わせには返信を行っておりませんので、ご了承ください。
    <ul>
      <li>大阪府東大阪市</li>
      <li><a href="https://t.co/93yqCB7Cqv">https://t.co/93yqCB7Cqv</a></li>
      <li>2010年12月に登録</li>
    </ul>
    <div>
     <p class="btn">
       <%= link_to "ツイート", new_tweet_path %>
       <a href="#">メールを送る</a>
     </p>
    </div>

app/views/tweets/_tem.html.erb
<p>
  <%= f.label :messesge, 'メッセージ' %>
  <%= f.text_field :messesge, :size => "20x10" %>
</p>

app/views/tweets/edit.html.erb
<%= form_for @tweet, url: {action: :update} do |f| %>
<p>
<%=render"tem",f: f %>
</p>
<%= f.submit '更新' %>
<% end %>

app/views/tweets/index.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
<meta charset='utf-8'>
<link rel="stylesheet" type="text/css" href="app/assets/stylesheet/tweets.scss">
</head>
<body>
  <div id="sidebar">
  </div>

  <div id="content">
    <% @tweets.each do |tweet| %>
<p>
  <table style="border-style: none;" border="1">
<td style="border-style: none;"><a href="#">ツイート　</a></td>
<td style="border-style: none;"><a href="#"><font color="#00CCFF">ツイートと返信　</frnt></a></td>
<td style="border-style: none;"><a href="#"><font color="#00CCFF">メディア</frnt></a></td>
</tr>
</table>
<table style="border-style: none;" border="1">
<td style="border-style: none;"><img src="assets/kindai.png" width="50" height="50" style="border-radius:400px;" ></td>
  <td style="border-style: none;"><a href="https://swdev-matuoka.c9users.io/">近畿大学</a></td>
  <td style="border-style: none;">@kinkidaigakuPR・</td>
  <td style="border-style: none;"><%= (Time.current - tweet.tdate).to_i / 60 %>分前</td>
</table>
  <br>
  <%= tweet.messesge %>
  <br>
  <br>
  <%= link_to '見る',tweet_path(tweet)%>
  <%= link_to '削除', tweet_path(tweet), method: :delete %>
  <%= link_to '編集', edit_tweet_path(tweet) %>
</p>
<hr>
<% end %>
  </div>
  <p>
  Copyright 2018 LIG inc.kinkidaigakuPR
  </p>
</body>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
<h3>エラーがあります。</h3> 
<ul>
<% @tweet.errors.full_messages.each do |msg| %>
<li>
  <%= msg %>
</li>
<% end %>
</ul>
<% end %> 

<%= form_for @tweet , url: {action: :create} do |f| %>
<%=render"tem",f: f %>
<%= f.submit 'ツイート' %>
<% end %>

app/views/tweets/show.html.erb
 <%= @tweets.messesge %>
 <%= (Time.current - @tweets.tdate).to_i / 60 %>分前
<%= link_to '戻る', '/' %>